---
# tasks file for consul-linux
- name: Remove files.
  file:
    state: absent
    path: "/tmp/{{ item }}"
  with_items:
  - consul_0.7.0_linux_amd64.zip
  - consul
- name: Download the package.
  get_url:
    url: https://releases.hashicorp.com/consul/0.7.0/consul_0.7.0_linux_amd64.zip
    dest: /tmp
    mode: 0777
- name: Install unzip
  apt:
    name: zip
  become: "{{ consul_nonroot }}"
- name: Unzip the package.
  command: unzip /tmp/consul_0.7.0_linux_amd64.zip -d /tmp
- name: Install consul
  copy:
    src: /tmp/consul
    dest: /usr/bin
    remote_src: yes
  become: "{{ consul_nonroot }}"
- name: Remove files.
  file:
    state: absent
    path: "/tmp/{{ item }}"
  with_items:
  - consul_0.7.0_linux_amd64.zip
  - consul
